# Generated by Django 5.1.3 on 2024-12-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('driving_license_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lainaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField()),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaus_app.car')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lainaus_app.student')),
            ],
        ),
    ]
