# Generated by Django 5.1.3 on 2024-12-04 20:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lainaus_app', '0002_lainaus_palautus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkki', models.CharField(max_length=100)),
                ('malli', models.CharField(max_length=100)),
                ('vuosi', models.IntegerField()),
                ('väri', models.CharField(max_length=50)),
                ('rekisterikilpi', models.CharField(max_length=20, unique=True)),
                ('kilometrimäärä', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Opiskelija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=100)),
                ('sukunimi', models.CharField(max_length=100)),
                ('opiskelija_id', models.CharField(max_length=50, unique=True)),
                ('ajokortti_id', models.CharField(max_length=50, unique=True)),
                ('puhelinnumero', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='lainaus',
            name='car',
        ),
        migrations.RemoveField(
            model_name='lainaus',
            name='student',
        ),
        migrations.RenameField(
            model_name='lainaus',
            old_name='palautus_date',
            new_name='palautus_päivä',
        ),
        migrations.RenameField(
            model_name='lainaus',
            old_name='barcode',
            new_name='viivakoodi',
        ),
        migrations.RemoveField(
            model_name='lainaus',
            name='loan_date',
        ),
        migrations.AddField(
            model_name='lainaus',
            name='lainaus_päivä',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lainaus',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lainaus_app.auto'),
        ),
        migrations.AddField(
            model_name='lainaus',
            name='opiskelija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lainaus_app.opiskelija'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
